spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/autoplan
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      #      ddl-auto: create-drop
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  web:
    resources:
      add-mapping: true
  devtools:
    restart:
      enabled: true
      additional-exclude: META-INF/**, application.yml
    livereload:
      enabled: true
  freemarker:
    cache: false
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace




